version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - BACKEND=emulation
      - EMULATION_SPEED=100
      - ZEROCONF_OVERWRITE=192.168.2.11/24,Mimoja-Datenschleuder
