name: Generate ZIP on push

on:
  push:
    branches:
      - main
      - dev
      - mimoja_dev
  pull_request:

jobs:
  build_zip:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_VERSIONING }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install ubuntu dependencies
      run: |
        sudo apt update
        sudo apt install -y libcairo2-dev libxt-dev libgirepository1.0-dev libgstreamer1.0-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
      # Call pytest here:
      # pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    
    # - name: Upload pytest test results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: pytest-results-${{ matrix.python-version }}
    #     path: junit/test-results-${{ matrix.python-version }}.xml
    #   # Use always() to always run this step to publish test results when there are test failures
    #   if: ${{ always() }}

    - name: Create folder to copy the files
      run: |
        mkdir -p meticulous-backend

    - name: Copy files, excep the folder meticulous using exclude 
      run: |
        rsync -avq --exclude='meticulous-backend' --exclude='dist' --exclude='.github' --exclude='.git' ./ meticulous-backend

    - uses: montudor/action-zip@v1
      name: Preparing ZIP
      with:
        args: zip -qq -r meticulous-backend.zip meticulous-backend

    - name: upload files
      uses: actions/upload-artifact@v2
      with:
        name: Update_files_backend
        path: meticulous-backend.zip
