name: Generate Update File
on:
  pull_request:
    types: [closed]
    branches:
      - feature/workflow_to_release
jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event.pull_request.merged == true || github.event.pull_request.rebase == true ) && github.event.pull_request.base.ref == 'feature/workflow_to_release'
    steps:
      - uses: actions/checkout@v3

      - name: Cache library
        uses: actions/cache@v2
        with:
          path: requirements.txt
          key: ${{ runner.os }}-library-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-library-

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Update version
        run: python update-version.py patch

      - name: Set Version
        run: | 
          echo "BUILD_VERSION=$(python -c 'from version import VERSION; print(VERSION)')" >> $GITHUB_ENV

      - name: Add, commit and push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'feature/workflow_to_release'
          directory: './'
          github_token: ${{ secrets.G_CLONE_TOKEN }}
      - run: |
          git config --global user.name "Gab0JS"
          git config --global user.email "gabriel.julian.s.morales.martinez@gmail.com"
          git add version.py
          git commit -m "New version ${{ env.BUILD_VERSION }}, Update version from Workflow"
          git push origin feature/workflow_to_release

      - name: Create folder to copy the files
        run: |
          mkdir -p meticulous/library 
          mkdir -p meticulous/backend_for_esp32 

      - name: Copy files, excep the folder meticulous using exclude 
        run: |
          rsync -avq --exclude='meticulous' ./ meticulous/backend_for_esp32/

      - name: Create folder to save library
        run: |
          mkdir -p library

      - name: Create virtual environment, download dependencies and copy them to the library folder of meticulous
        run: |
          python3 -m venv venv && source venv/bin/activate
          cd library
          pip download -r ../requirements.txt
          deactivate
          cp -rf . ../meticulous/library/
          cd

      - name: upload files
        uses: actions/upload-artifact@v2
        with:
          name: Update_files_backend
          path: meticulous

      - uses: montudor/action-zip@v1
        name: Preparing ZIP
        with:
          args: zip -qq -r update_back.zip meticulous/

      - name: Release
        env:
          GITHUB_TOKEN: "${{ secrets.G_CLONE_TOKEN }}"
        run: |
          gh release create backend_for_esp32-${{ env.BUILD_VERSION }} update_back.zip -R https://github.com/FFFuego/Meticulous-Releases
          echo "Release created, And version updated to ${{ env.BUILD_VERSION }}"